DOCTORS = [
    {
        "id": 1,
        "name": "Dr. Priya Sharma",
        "specialty": "Cardiologist",
        "experience": 12,
        "rating": 4.9,
        "reviews": 1243,
        "fee_chat": 199,
        "fee_audio": 299,
        "fee_video": 499,
        "discount": 20,
        "image": "https://randomuser.me/api/portraits/women/44.jpg",
        "languages": ["English", "Hindi"],
        "available": True,
        "slots": ["10:00 AM", "11:30 AM", "02:00 PM", "04:30 PM"],
        "education": "MBBS, MD (Cardiology) — AIIMS Delhi",
        "hospital": "Apollo Hospital, Mumbai",
        "about": "Dr. Priya Sharma is a senior cardiologist with 12 years of experience in treating heart disease, hypertension, and cardiac rehabilitation.",
        "symptoms_treated": ["Chest pain", "Hypertension", "Heart palpitations", "Shortness of breath"]
    },
    {
        "id": 2,
        "name": "Dr. Arjun Mehta",
        "specialty": "General Physician",
        "experience": 8,
        "rating": 4.7,
        "reviews": 3421,
        "fee_chat": 199,
        "fee_audio": 249,
        "fee_video": 399,
        "discount": 15,
        "image": "https://randomuser.me/api/portraits/men/32.jpg",
        "languages": ["English", "Hindi", "Gujarati"],
        "available": True,
        "slots": ["09:00 AM", "10:30 AM", "12:00 PM", "03:00 PM", "05:00 PM"],
        "education": "MBBS — KEM Hospital, Mumbai",
        "hospital": "Fortis Healthcare, Delhi",
        "about": "Dr. Arjun Mehta is a trusted general physician known for accurate diagnosis and compassionate care for fever, infections, and chronic conditions.",
        "symptoms_treated": ["Fever", "Cold & cough", "Body pain", "Fatigue", "Infections"]
    },
    {
        "id": 3,
        "name": "Dr. Sneha Kapoor",
        "specialty": "Dermatologist",
        "experience": 9,
        "rating": 4.8,
        "reviews": 2187,
        "fee_chat": 249,
        "fee_audio": 349,
        "fee_video": 549,
        "discount": 10,
        "image": "https://randomuser.me/api/portraits/women/68.jpg",
        "languages": ["English", "Hindi"],
        "available": True,
        "slots": ["11:00 AM", "01:00 PM", "03:30 PM", "05:30 PM"],
        "education": "MBBS, MD (Dermatology) — Manipal University",
        "hospital": "Skin & You Clinic, Bangalore",
        "about": "Dr. Sneha Kapoor specialises in treating acne, eczema, psoriasis, and cosmetic skin conditions with evidence-based treatments.",
        "symptoms_treated": ["Acne", "Eczema", "Psoriasis", "Hair loss", "Skin rashes"]
    },
    {
        "id": 4,
        "name": "Dr. Ravi Nair",
        "specialty": "Diabetologist",
        "experience": 15,
        "rating": 4.9,
        "reviews": 4320,
        "fee_chat": 299,
        "fee_audio": 399,
        "fee_video": 599,
        "discount": 25,
        "image": "https://randomuser.me/api/portraits/men/55.jpg",
        "languages": ["English", "Malayalam", "Hindi"],
        "available": True,
        "slots": ["08:30 AM", "10:00 AM", "02:30 PM", "04:00 PM"],
        "education": "MBBS, MD (Medicine), DM (Endocrinology) — CMC Vellore",
        "hospital": "Medanta Hospital, Gurugram",
        "about": "Dr. Ravi Nair is a leading diabetologist and endocrinologist with 15 years of expertise in managing Type 1, Type 2 diabetes, and thyroid disorders.",
        "symptoms_treated": ["High blood sugar", "Diabetes management", "Thyroid issues", "Weight gain", "Fatigue"]
    },
    {
        "id": 5,
        "name": "Dr. Ananya Roy",
        "specialty": "Gynaecologist",
        "experience": 11,
        "rating": 4.8,
        "reviews": 1876,
        "fee_chat": 249,
        "fee_audio": 349,
        "fee_video": 549,
        "discount": 20,
        "image": "https://randomuser.me/api/portraits/women/33.jpg",
        "languages": ["English", "Bengali", "Hindi"],
        "available": True,
        "slots": ["10:00 AM", "12:30 PM", "03:00 PM", "05:00 PM"],
        "education": "MBBS, MS (Obstetrics & Gynaecology) — PGIMER Chandigarh",
        "hospital": "Rainbow Children's Hospital, Hyderabad",
        "about": "Dr. Ananya Roy is an experienced gynaecologist providing care for menstrual disorders, pregnancy, PCOS, and reproductive health.",
        "symptoms_treated": ["PCOS", "Menstrual irregularities", "Pregnancy care", "Fertility issues", "Vaginal infections"]
    },
    {
        "id": 6,
        "name": "Dr. Vikram Singh",
        "specialty": "Psychiatrist",
        "experience": 10,
        "rating": 4.7,
        "reviews": 987,
        "fee_chat": 349,
        "fee_audio": 449,
        "fee_video": 649,
        "discount": 15,
        "image": "https://randomuser.me/api/portraits/men/76.jpg",
        "languages": ["English", "Hindi"],
        "available": True,
        "slots": ["09:30 AM", "11:00 AM", "02:00 PM", "04:30 PM"],
        "education": "MBBS, MD (Psychiatry) — NIMHANS Bangalore",
        "hospital": "Vandrevala Foundation, Mumbai",
        "about": "Dr. Vikram Singh is a compassionate psychiatrist specialising in anxiety, depression, OCD, and stress management with a holistic approach.",
        "symptoms_treated": ["Anxiety", "Depression", "Insomnia", "OCD", "Stress", "Panic attacks"]
    },
    {
        "id": 7,
        "name": "Dr. Meena Pillai",
        "specialty": "Paediatrician",
        "experience": 14,
        "rating": 4.9,
        "reviews": 5432,
        "fee_chat": 199,
        "fee_audio": 299,
        "fee_video": 449,
        "discount": 30,
        "image": "https://randomuser.me/api/portraits/women/57.jpg",
        "languages": ["English", "Malayalam", "Tamil", "Hindi"],
        "available": True,
        "slots": ["08:00 AM", "10:00 AM", "12:00 PM", "03:00 PM"],
        "education": "MBBS, MD (Paediatrics) — Kasturba Medical College",
        "hospital": "Cloudnine Hospital, Chennai",
        "about": "Dr. Meena Pillai is a well-known paediatrician with 14 years of experience in child health, vaccinations, and developmental care.",
        "symptoms_treated": ["Fever", "Child infections", "Vaccination", "Growth issues", "Respiratory illness"]
    },
    {
        "id": 8,
        "name": "Dr. Siddharth Joshi",
        "specialty": "Orthopaedist",
        "experience": 13,
        "rating": 4.6,
        "reviews": 2341,
        "fee_chat": 299,
        "fee_audio": 399,
        "fee_video": 599,
        "discount": 10,
        "image": "https://randomuser.me/api/portraits/men/41.jpg",
        "languages": ["English", "Hindi", "Marathi"],
        "available": False,
        "slots": ["10:30 AM", "01:30 PM", "04:00 PM"],
        "education": "MBBS, MS (Orthopaedics) — Seth GS Medical College, Mumbai",
        "hospital": "Kokilaben Dhirubhai Ambani Hospital, Mumbai",
        "about": "Dr. Siddharth Joshi specialises in joint replacement, sports injuries, spine disorders, and fracture management.",
        "symptoms_treated": ["Joint pain", "Back pain", "Fractures", "Sports injuries", "Arthritis"]
    },
]

SPECIALTIES = [
    "General Physician", "Cardiologist", "Dermatologist", "Diabetologist",
    "Gynaecologist", "Psychiatrist", "Paediatrician", "Orthopaedist",
    "Neurologist", "Pulmonologist", "ENT Specialist", "Ophthalmologist"
]

AI_SYMPTOM_MAP = {
    "chest pain":       [1],   # Cardiologist
    "heart":            [1],
    "palpitation":      [1],
    "fever":            [2, 7],
    "cold":             [2],
    "cough":            [2],
    "infection":        [2],
    "skin":             [3],
    "acne":             [3],
    "rash":             [3],
    "hair":             [3],
    "diabetes":         [4],
    "sugar":            [4],
    "thyroid":          [4],
    "period":           [5],
    "pcos":             [5],
    "pregnancy":        [5],
    "anxiety":          [6],
    "depression":       [6],
    "stress":           [6],
    "sleep":            [6],
    "child":            [7],
    "baby":             [7],
    "vaccination":      [7],
    "joint":            [8],
    "back pain":        [8],
    "fracture":         [8],
}
