# ── Image helper ──────────────────────────────────────────────────────────────
# Using real medicine pill/pack photos from Wikimedia Commons (public domain)
# and open pharmaceutical image CDNs. All URLs are publicly accessible.
# Format: IMG[category_color] used as fallback if URL fails.
# ──────────────────────────────────────────────────────────────────────────────

MEDICINES = [

    # ═══════════════ PAIN RELIEF ═══════════════
    {
        "id": 1,
        "name": "Paracetamol 500mg",
        "brand": "Crocin",
        "category": "Pain Relief",
        "price": 32,
        "mrp": 45,
        "discount": 29,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Paracetamol_tablets.jpg/320px-Paracetamol_tablets.jpg",
        "description": "Paracetamol is the most widely used over-the-counter analgesic and antipyretic. It effectively treats mild to moderate pain and reduces fever without irritating the stomach lining.",
        "uses": ["Fever", "Headache", "Body pain", "Toothache", "Post-vaccination fever"],
        "dosage": "1 tablet every 4–6 hours. Do not exceed 8 tablets in 24 hours.",
        "precautions": ["Avoid alcohol", "Not for liver disease patients", "Consult doctor if pregnant"],
        "side_effects": ["Nausea", "Allergic reactions (rare)", "Liver damage if overdosed"],
        "interactions": ["Warfarin", "Alcohol", "Other paracetamol-containing products"],
        "manufacturer": "GSK Pharmaceuticals",
        "pack_size": "15 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 12430,
        "tags": ["fever", "pain", "headache", "paracetamol"]
    },
    {
        "id": 2,
        "name": "Ibuprofen 400mg",
        "brand": "Brufen",
        "category": "Pain Relief",
        "price": 25,
        "mrp": 35,
        "discount": 29,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Ibuprofen_200mg_Queisser.jpg/320px-Ibuprofen_200mg_Queisser.jpg",
        "description": "Ibuprofen is a non-steroidal anti-inflammatory drug (NSAID) that reduces hormones causing inflammation and pain in the body.",
        "uses": ["Pain", "Inflammation", "Fever", "Arthritis", "Menstrual cramps"],
        "dosage": "400mg 3 times daily after food.",
        "precautions": ["Always take with food", "Not for stomach ulcers", "Avoid in kidney disease"],
        "side_effects": ["Stomach upset", "Heartburn", "Dizziness", "Kidney issues (long-term)"],
        "interactions": ["Aspirin", "Warfarin", "ACE inhibitors", "Lithium"],
        "manufacturer": "Abbott India",
        "pack_size": "10 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.3,
        "reviews": 8760,
        "tags": ["pain", "inflammation", "fever", "nsaid", "ibuprofen"]
    },
    {
        "id": 3,
        "name": "Diclofenac 50mg",
        "brand": "Voveran",
        "category": "Pain Relief",
        "price": 38,
        "mrp": 52,
        "discount": 27,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Diclofenac_tablets.jpg/320px-Diclofenac_tablets.jpg",
        "description": "Diclofenac is an NSAID used to relieve pain and inflammation in conditions such as arthritis, muscle pain, and sports injuries.",
        "uses": ["Arthritis", "Muscle pain", "Back pain", "Sports injuries", "Dental pain"],
        "dosage": "50mg two to three times daily with food.",
        "precautions": ["Take with food or milk", "Not for heart disease patients", "Avoid in last trimester of pregnancy"],
        "side_effects": ["Stomach pain", "Nausea", "Headache", "Dizziness", "Elevated blood pressure"],
        "interactions": ["Aspirin", "Warfarin", "Lithium", "Methotrexate"],
        "manufacturer": "Novartis India",
        "pack_size": "10 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.2,
        "reviews": 5430,
        "tags": ["pain", "arthritis", "anti-inflammatory", "diclofenac"]
    },
    {
        "id": 4,
        "name": "Tramadol 50mg",
        "brand": "Ultram",
        "category": "Pain Relief",
        "price": 120,
        "mrp": 158,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Tramadol_50mg_capsules.jpg/320px-Tramadol_50mg_capsules.jpg",
        "description": "Tramadol is an opioid pain medication used to treat moderate to moderately severe pain, including post-operative pain.",
        "uses": ["Moderate to severe pain", "Post-operative pain", "Chronic pain management"],
        "dosage": "50–100mg every 4–6 hours as needed. Maximum 400mg/day.",
        "precautions": ["Risk of dependency", "Do not drive", "Avoid alcohol", "Not for epilepsy patients"],
        "side_effects": ["Dizziness", "Nausea", "Constipation", "Drowsiness", "Sweating"],
        "interactions": ["MAO inhibitors", "SSRIs", "Alcohol", "Sedatives"],
        "manufacturer": "Johnson & Johnson",
        "pack_size": "10 capsules",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.1,
        "reviews": 3210,
        "tags": ["pain", "opioid", "severe pain", "tramadol"]
    },

    # ═══════════════ ANTIBIOTICS ═══════════════
    {
        "id": 5,
        "name": "Azithromycin 500mg",
        "brand": "Azithral",
        "category": "Antibiotics",
        "price": 85,
        "mrp": 110,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Zithromax_250_mg_Z-Pak.jpg/320px-Zithromax_250_mg_Z-Pak.jpg",
        "description": "Azithromycin is a macrolide antibiotic that fights bacteria in the body and is used for a wide range of bacterial infections.",
        "uses": ["Chest infections", "Throat infections", "Skin infections", "Ear infections", "Typhoid"],
        "dosage": "500mg once daily for 3 days as prescribed.",
        "precautions": ["Complete full course", "Not for viral infections", "Consult doctor before use"],
        "side_effects": ["Diarrhea", "Nausea", "Stomach pain", "Vomiting"],
        "interactions": ["Antacids", "Warfarin", "Digoxin"],
        "manufacturer": "Alembic Pharmaceuticals",
        "pack_size": "3 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.3,
        "reviews": 8760,
        "tags": ["antibiotic", "infection", "bacteria", "azithromycin"]
    },
    {
        "id": 6,
        "name": "Amoxicillin 500mg",
        "brand": "Mox 500",
        "category": "Antibiotics",
        "price": 78,
        "mrp": 102,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Amoxicillin_500mg_capsules.jpg/320px-Amoxicillin_500mg_capsules.jpg",
        "description": "Amoxicillin is a penicillin-type antibiotic widely prescribed for bacterial infections of the ear, nose, throat, lungs, skin, and urinary tract.",
        "uses": ["Ear infections", "Throat infections", "Urinary tract infections", "Pneumonia", "Sinusitis"],
        "dosage": "500mg every 8 hours as prescribed.",
        "precautions": ["Check for penicillin allergy", "Complete full course", "Store below 25°C"],
        "side_effects": ["Diarrhea", "Rash", "Nausea", "Vomiting"],
        "interactions": ["Methotrexate", "Warfarin", "Other antibiotics"],
        "manufacturer": "Ranbaxy Laboratories",
        "pack_size": "10 capsules",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.2,
        "reviews": 6540,
        "tags": ["antibiotic", "infection", "penicillin", "amoxicillin"]
    },
    {
        "id": 7,
        "name": "Ciprofloxacin 500mg",
        "brand": "Ciplox",
        "category": "Antibiotics",
        "price": 92,
        "mrp": 122,
        "discount": 25,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Ciprofloxacin_500mg.jpg/320px-Ciprofloxacin_500mg.jpg",
        "description": "Ciprofloxacin is a fluoroquinolone antibiotic used for urinary tract infections, respiratory infections, and other serious bacterial infections.",
        "uses": ["UTI", "Respiratory infections", "Typhoid", "Bone and joint infections", "Anthrax exposure"],
        "dosage": "500mg twice daily for 7–14 days as prescribed.",
        "precautions": ["Avoid sun exposure", "Stay hydrated", "Not for children under 18", "Avoid antacids"],
        "side_effects": ["Nausea", "Diarrhea", "Dizziness", "Tendon damage (rare)", "Photosensitivity"],
        "interactions": ["Antacids", "Warfarin", "Theophylline", "NSAIDs"],
        "manufacturer": "Cipla Limited",
        "pack_size": "10 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.4,
        "reviews": 4320,
        "tags": ["antibiotic", "uti", "infection", "fluoroquinolone"]
    },
    {
        "id": 8,
        "name": "Doxycycline 100mg",
        "brand": "Doxt SL",
        "category": "Antibiotics",
        "price": 68,
        "mrp": 88,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Doxycycline_100mg_capsules.jpg/320px-Doxycycline_100mg_capsules.jpg",
        "description": "Doxycycline is a tetracycline antibiotic used to treat bacterial infections including acne, pneumonia, chlamydia, and Lyme disease.",
        "uses": ["Acne", "Pneumonia", "Chlamydia", "Lyme disease", "Malaria prevention"],
        "dosage": "100mg once or twice daily with plenty of water.",
        "precautions": ["Take with food", "Avoid sun exposure", "Not for pregnant women or children under 8"],
        "side_effects": ["Photosensitivity", "Nausea", "Esophageal irritation", "Yeast infection"],
        "interactions": ["Antacids", "Iron supplements", "Penicillins", "Warfarin"],
        "manufacturer": "Sun Pharmaceutical",
        "pack_size": "10 capsules",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.1,
        "reviews": 2980,
        "tags": ["antibiotic", "acne", "malaria", "tetracycline"]
    },

    # ═══════════════ ALLERGY ═══════════════
    {
        "id": 9,
        "name": "Cetirizine 10mg",
        "brand": "Zyrtec",
        "category": "Allergy",
        "price": 28,
        "mrp": 38,
        "discount": 26,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Cetirizine_Hydrochloride_10_mg_Tablets.jpg/320px-Cetirizine_Hydrochloride_10_mg_Tablets.jpg",
        "description": "Cetirizine is a second-generation antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching, sneezing, and hives.",
        "uses": ["Hay fever", "Runny nose", "Itchy eyes", "Skin rash", "Hives", "Dust allergy"],
        "dosage": "One 10mg tablet once daily.",
        "precautions": ["May cause drowsiness", "Avoid driving", "Not for children under 2 years"],
        "side_effects": ["Drowsiness", "Dry mouth", "Headache", "Fatigue"],
        "interactions": ["Alcohol", "CNS depressants", "Sedatives"],
        "manufacturer": "UCB India",
        "pack_size": "10 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.6,
        "reviews": 21870,
        "tags": ["allergy", "antihistamine", "cold", "cetirizine"]
    },
    {
        "id": 10,
        "name": "Fexofenadine 120mg",
        "brand": "Allegra",
        "category": "Allergy",
        "price": 65,
        "mrp": 85,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Allegra_120_mg_tablets.jpg/320px-Allegra_120_mg_tablets.jpg",
        "description": "Fexofenadine is a non-drowsy antihistamine that provides 24-hour relief from allergy symptoms without causing significant sedation.",
        "uses": ["Seasonal allergies", "Hay fever", "Urticaria", "Itchy skin", "Allergic rhinitis"],
        "dosage": "120mg once daily or 180mg once daily for urticaria.",
        "precautions": ["Do not take with fruit juice", "Consult doctor if kidney disease", "Safe for driving"],
        "side_effects": ["Headache", "Drowsiness (rare)", "Nausea", "Dizziness"],
        "interactions": ["Antacids with aluminium or magnesium", "Erythromycin", "Ketoconazole"],
        "manufacturer": "Sanofi India",
        "pack_size": "10 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.7,
        "reviews": 15430,
        "tags": ["allergy", "non-drowsy", "antihistamine", "fexofenadine"]
    },
    {
        "id": 11,
        "name": "Loratadine 10mg",
        "brand": "Claritin",
        "category": "Allergy",
        "price": 42,
        "mrp": 58,
        "discount": 28,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Loratadine_10_mg_tablet.jpg/320px-Loratadine_10_mg_tablet.jpg",
        "description": "Loratadine is a fast-acting, non-drowsy antihistamine that relieves allergy symptoms including runny nose, sneezing, and itchy watery eyes.",
        "uses": ["Allergic rhinitis", "Hives", "Skin allergy", "Sneezing", "Itchy eyes"],
        "dosage": "10mg once daily.",
        "precautions": ["Reduce dose in liver disease", "Consult doctor if pregnant"],
        "side_effects": ["Headache", "Dry mouth", "Fatigue", "Nervousness"],
        "interactions": ["Ketoconazole", "Erythromycin", "Cimetidine"],
        "manufacturer": "Bayer Consumer Health",
        "pack_size": "10 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 9870,
        "tags": ["allergy", "non-drowsy", "antihistamine", "loratadine"]
    },

    # ═══════════════ DIABETES ═══════════════
    {
        "id": 12,
        "name": "Metformin 500mg",
        "brand": "Glycomet",
        "category": "Diabetes",
        "price": 42,
        "mrp": 55,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Metformin_500mg_tablets.jpg/320px-Metformin_500mg_tablets.jpg",
        "description": "Metformin is the first-line oral medication for type 2 diabetes. It works by decreasing hepatic glucose production and improving insulin sensitivity.",
        "uses": ["Type 2 Diabetes", "Blood sugar control", "Insulin resistance", "Polycystic ovary syndrome"],
        "dosage": "500mg twice daily with meals as prescribed.",
        "precautions": ["Monitor blood sugar regularly", "Avoid alcohol", "Not for kidney disease"],
        "side_effects": ["Nausea", "Diarrhea", "Stomach upset", "Lactic acidosis (rare)"],
        "interactions": ["Alcohol", "Contrast dyes", "Some diuretics"],
        "manufacturer": "USV Private Limited",
        "pack_size": "20 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.4,
        "reviews": 34210,
        "tags": ["diabetes", "sugar", "insulin", "metformin"]
    },
    {
        "id": 13,
        "name": "Glimepiride 2mg",
        "brand": "Amaryl",
        "category": "Diabetes",
        "price": 58,
        "mrp": 76,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Glimepiride_2mg_tablets.jpg/320px-Glimepiride_2mg_tablets.jpg",
        "description": "Glimepiride is a sulfonylurea antidiabetic drug used alongside diet and exercise to control blood sugar levels in type 2 diabetes.",
        "uses": ["Type 2 Diabetes", "Blood glucose control"],
        "dosage": "1–4mg once daily with breakfast.",
        "precautions": ["Monitor blood sugar", "Risk of hypoglycemia", "Avoid alcohol", "Not for Type 1 diabetes"],
        "side_effects": ["Hypoglycemia", "Nausea", "Dizziness", "Weight gain"],
        "interactions": ["Alcohol", "NSAIDs", "Beta blockers", "Warfarin"],
        "manufacturer": "Sanofi India",
        "pack_size": "15 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.3,
        "reviews": 7650,
        "tags": ["diabetes", "blood sugar", "sulfonylurea", "glimepiride"]
    },
    {
        "id": 14,
        "name": "Sitagliptin 50mg",
        "brand": "Januvia",
        "category": "Diabetes",
        "price": 245,
        "mrp": 320,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Sitagliptin_phosphate_100mg.jpg/320px-Sitagliptin_phosphate_100mg.jpg",
        "description": "Sitagliptin is a DPP-4 inhibitor that lowers blood sugar levels by increasing insulin production and decreasing glucagon levels.",
        "uses": ["Type 2 Diabetes", "Blood sugar control as add-on therapy"],
        "dosage": "50mg or 100mg once daily.",
        "precautions": ["Monitor kidney function", "Not for Type 1 diabetes", "Pancreatitis risk"],
        "side_effects": ["Upper respiratory infection", "Headache", "Nasopharyngitis", "Pancreatitis (rare)"],
        "interactions": ["Digoxin", "Insulin", "Sulfonylureas"],
        "manufacturer": "MSD Pharmaceuticals",
        "pack_size": "14 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 5430,
        "tags": ["diabetes", "DPP4", "blood sugar", "sitagliptin"]
    },

    # ═══════════════ GASTRIC ═══════════════
    {
        "id": 15,
        "name": "Omeprazole 20mg",
        "brand": "Omez",
        "category": "Gastric",
        "price": 55,
        "mrp": 72,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Omeprazole_20_mg_capsules.jpg/320px-Omeprazole_20_mg_capsules.jpg",
        "description": "Omeprazole is a proton pump inhibitor that reduces stomach acid production, used to treat acid reflux, GERD, and peptic ulcers.",
        "uses": ["Acid reflux", "GERD", "Stomach ulcers", "Heartburn", "Zollinger-Ellison syndrome"],
        "dosage": "20mg once daily before breakfast.",
        "precautions": ["Long-term use needs monitoring", "Not for immediate heartburn relief"],
        "side_effects": ["Headache", "Diarrhea", "Nausea", "Vitamin B12 deficiency (long-term)"],
        "interactions": ["Clopidogrel", "Methotrexate", "Warfarin"],
        "manufacturer": "Dr. Reddy's Laboratories",
        "pack_size": "10 capsules",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.7,
        "reviews": 56320,
        "tags": ["gastric", "acid", "reflux", "stomach", "omeprazole"]
    },
    {
        "id": 16,
        "name": "Pantoprazole 40mg",
        "brand": "Pan 40",
        "category": "Gastric",
        "price": 62,
        "mrp": 82,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Pantoprazole_40_mg_tablets.jpg/320px-Pantoprazole_40_mg_tablets.jpg",
        "description": "Pantoprazole is a proton pump inhibitor used to treat excessive stomach acid conditions including erosive esophagitis and GERD.",
        "uses": ["GERD", "Erosive esophagitis", "Stomach ulcers", "H. pylori eradication"],
        "dosage": "40mg once daily 30–60 minutes before a meal.",
        "precautions": ["Do not crush or chew tablet", "Monitor magnesium for long-term use"],
        "side_effects": ["Headache", "Diarrhea", "Abdominal pain", "Flatulence"],
        "interactions": ["Warfarin", "Methotrexate", "Atazanavir"],
        "manufacturer": "Alkem Laboratories",
        "pack_size": "15 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.6,
        "reviews": 32100,
        "tags": ["gastric", "acid", "gerd", "pantoprazole", "ppi"]
    },
    {
        "id": 17,
        "name": "Domperidone 10mg",
        "brand": "Domstal",
        "category": "Gastric",
        "price": 35,
        "mrp": 46,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Domperidone_10mg_tablets.jpg/320px-Domperidone_10mg_tablets.jpg",
        "description": "Domperidone is an antiemetic and prokinetic agent used to treat nausea, vomiting, and conditions where the stomach empties too slowly.",
        "uses": ["Nausea", "Vomiting", "Bloating", "Slow stomach emptying", "Acid reflux"],
        "dosage": "10mg three times daily before meals.",
        "precautions": ["Not for heart conditions", "Short-term use recommended", "Not for children under 12"],
        "side_effects": ["Dry mouth", "Headache", "Abdominal cramps", "Galactorrhea (rare)"],
        "interactions": ["Ketoconazole", "Erythromycin", "CYP3A4 inhibitors"],
        "manufacturer": "Torrent Pharmaceuticals",
        "pack_size": "10 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.4,
        "reviews": 18760,
        "tags": ["gastric", "nausea", "vomiting", "domperidone", "antiemetic"]
    },
    {
        "id": 18,
        "name": "Ondansetron 4mg",
        "brand": "Emeset",
        "category": "Gastric",
        "price": 48,
        "mrp": 64,
        "discount": 25,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Ondansetron_4mg_tablets.jpg/320px-Ondansetron_4mg_tablets.jpg",
        "description": "Ondansetron is a serotonin 5-HT3 receptor antagonist used to prevent nausea and vomiting caused by chemotherapy, radiation, and surgery.",
        "uses": ["Chemotherapy-induced nausea", "Post-surgery nausea", "Radiation-induced nausea", "Gastroenteritis"],
        "dosage": "4–8mg up to 3 times daily as prescribed.",
        "precautions": ["Monitor heart rhythm", "Not with apomorphine", "Consult doctor if liver disease"],
        "side_effects": ["Headache", "Constipation", "Fatigue", "QT prolongation (rare)"],
        "interactions": ["Apomorphine", "Tramadol", "QT-prolonging drugs"],
        "manufacturer": "Cipla Limited",
        "pack_size": "10 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 9870,
        "tags": ["nausea", "vomiting", "antiemetic", "chemotherapy", "ondansetron"]
    },

    # ═══════════════ CARDIAC ═══════════════
    {
        "id": 19,
        "name": "Atorvastatin 10mg",
        "brand": "Lipitor",
        "category": "Cardiac",
        "price": 98,
        "mrp": 130,
        "discount": 25,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Lipitor_pills.jpg/320px-Lipitor_pills.jpg",
        "description": "Atorvastatin is a statin medication used to prevent cardiovascular disease and lower blood cholesterol levels.",
        "uses": ["High cholesterol", "Heart disease prevention", "Stroke prevention", "Triglyceride reduction"],
        "dosage": "10–80mg once daily as prescribed.",
        "precautions": ["Regular liver tests", "Avoid grapefruit juice", "Not for pregnancy"],
        "side_effects": ["Muscle pain", "Liver enzyme elevation", "Headache", "Digestive issues"],
        "interactions": ["Grapefruit juice", "Fibrates", "Niacin", "Cyclosporine"],
        "manufacturer": "Pfizer India",
        "pack_size": "10 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 28760,
        "tags": ["cholesterol", "heart", "cardiac", "statin", "atorvastatin"]
    },
    {
        "id": 20,
        "name": "Losartan 50mg",
        "brand": "Losacar",
        "category": "Cardiac",
        "price": 72,
        "mrp": 95,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Losartan_50mg_tablets.jpg/320px-Losartan_50mg_tablets.jpg",
        "description": "Losartan is an angiotensin receptor blocker (ARB) used to treat high blood pressure and reduce the risk of stroke.",
        "uses": ["Hypertension", "Heart failure", "Kidney protection in diabetes", "Stroke prevention"],
        "dosage": "50mg once daily or as prescribed.",
        "precautions": ["Monitor blood pressure", "Avoid potassium supplements", "Not for pregnancy"],
        "side_effects": ["Dizziness", "Fatigue", "Cough (rare)", "Elevated potassium"],
        "interactions": ["Potassium supplements", "NSAIDs", "Lithium"],
        "manufacturer": "Cadila Healthcare",
        "pack_size": "15 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.4,
        "reviews": 21340,
        "tags": ["blood pressure", "hypertension", "cardiac", "losartan"]
    },
    {
        "id": 21,
        "name": "Amlodipine 5mg",
        "brand": "Amlokind",
        "category": "Cardiac",
        "price": 55,
        "mrp": 72,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Amlodipine_besylate_5mg_tablets.jpg/320px-Amlodipine_besylate_5mg_tablets.jpg",
        "description": "Amlodipine is a calcium channel blocker used to treat high blood pressure and chest pain (angina).",
        "uses": ["Hypertension", "Angina", "Coronary artery disease", "Raynaud phenomenon"],
        "dosage": "5–10mg once daily.",
        "precautions": ["Do not stop suddenly", "Monitor blood pressure regularly", "Grapefruit interaction"],
        "side_effects": ["Ankle swelling", "Flushing", "Headache", "Dizziness", "Fatigue"],
        "interactions": ["Grapefruit juice", "Simvastatin", "Cyclosporine"],
        "manufacturer": "Mankind Pharma",
        "pack_size": "10 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 17430,
        "tags": ["blood pressure", "hypertension", "angina", "calcium channel blocker"]
    },
    {
        "id": 22,
        "name": "Aspirin 75mg",
        "brand": "Ecosprin",
        "category": "Cardiac",
        "price": 22,
        "mrp": 30,
        "discount": 27,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Aspirin_tablets.jpg/320px-Aspirin_tablets.jpg",
        "description": "Low-dose aspirin is used as an antiplatelet agent to prevent blood clots, heart attacks, and strokes in high-risk patients.",
        "uses": ["Heart attack prevention", "Stroke prevention", "Blood clot prevention", "Coronary artery disease"],
        "dosage": "75mg once daily after food.",
        "precautions": ["Take with food", "Not for children under 16", "Not for bleeding disorders"],
        "side_effects": ["Stomach bleeding", "Nausea", "Indigestion", "Allergic reactions"],
        "interactions": ["Warfarin", "Ibuprofen", "Heparin", "Alcohol"],
        "manufacturer": "USV Pharmaceuticals",
        "pack_size": "14 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.6,
        "reviews": 45230,
        "tags": ["heart", "antiplatelet", "stroke", "aspirin", "cardiac"]
    },

    # ═══════════════ VITAMINS & SUPPLEMENTS ═══════════════
    {
        "id": 23,
        "name": "Vitamin D3 60000 IU",
        "brand": "D-Rise",
        "category": "Vitamins",
        "price": 145,
        "mrp": 180,
        "discount": 19,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Vitamin_D_supplement_pills.jpg/320px-Vitamin_D_supplement_pills.jpg",
        "description": "High-dose Vitamin D3 sachets used to treat and prevent Vitamin D deficiency, essential for calcium absorption and bone health.",
        "uses": ["Vitamin D deficiency", "Bone health", "Immune support", "Calcium absorption", "Muscle weakness"],
        "dosage": "One sachet weekly or as directed by doctor.",
        "precautions": ["Monitor Vitamin D levels", "Avoid excessive intake", "Take with food"],
        "side_effects": ["Nausea (if overdosed)", "Hypercalcemia (excess)", "Constipation"],
        "interactions": ["Thiazide diuretics", "Digoxin", "Aluminum antacids"],
        "manufacturer": "USV Private Limited",
        "pack_size": "4 sachets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.8,
        "reviews": 78910,
        "tags": ["vitamin", "bone", "immune", "supplement", "vitamin d"]
    },
    {
        "id": 24,
        "name": "Multivitamin Tablets",
        "brand": "Supradyn",
        "category": "Vitamins",
        "price": 185,
        "mrp": 230,
        "discount": 20,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Multivitamin_supplement_tablets.jpg/320px-Multivitamin_supplement_tablets.jpg",
        "description": "Complete multivitamin and multimineral supplement providing 12 vitamins and 11 minerals for daily nutritional support.",
        "uses": ["Nutritional deficiency", "Energy boost", "Immune support", "General wellness"],
        "dosage": "One tablet daily after breakfast.",
        "precautions": ["Do not exceed recommended dose", "Keep out of reach of children"],
        "side_effects": ["Nausea (rare)", "Urine discoloration (harmless)", "Constipation"],
        "interactions": ["Tetracycline antibiotics", "Levodopa", "Thyroid medications"],
        "manufacturer": "Bayer Pharmaceuticals",
        "pack_size": "30 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 98760,
        "tags": ["vitamin", "supplement", "nutrition", "wellness", "multivitamin"]
    },
    {
        "id": 25,
        "name": "Vitamin C 500mg",
        "brand": "Celin",
        "category": "Vitamins",
        "price": 45,
        "mrp": 60,
        "discount": 25,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Vitamin_C_tablets_500mg.jpg/320px-Vitamin_C_tablets_500mg.jpg",
        "description": "Vitamin C (Ascorbic acid) is an essential antioxidant vitamin that supports immune function, skin health, and collagen synthesis.",
        "uses": ["Vitamin C deficiency", "Immune support", "Skin health", "Antioxidant", "Iron absorption"],
        "dosage": "500mg once daily after food.",
        "precautions": ["High doses may cause kidney stones", "Avoid on empty stomach if sensitive"],
        "side_effects": ["Stomach upset", "Diarrhea (high doses)", "Kidney stones (very high doses)"],
        "interactions": ["Aspirin", "Warfarin", "Iron supplements (enhances absorption)"],
        "manufacturer": "GSK Pharmaceuticals",
        "pack_size": "30 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.7,
        "reviews": 43210,
        "tags": ["vitamin", "immune", "antioxidant", "vitamin c", "ascorbic acid"]
    },
    {
        "id": 26,
        "name": "Omega-3 Fish Oil 1000mg",
        "brand": "Seven Seas",
        "category": "Vitamins",
        "price": 320,
        "mrp": 420,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Fish_oil_capsules.jpg/320px-Fish_oil_capsules.jpg",
        "description": "Omega-3 Fish Oil capsules provide EPA and DHA essential fatty acids that support heart health, brain function, and reduce inflammation.",
        "uses": ["Heart health", "Brain function", "Joint inflammation", "Triglyceride reduction", "Eye health"],
        "dosage": "1–2 capsules daily with meals.",
        "precautions": ["May increase bleeding time", "Consult doctor before surgery", "Fish allergy caution"],
        "side_effects": ["Fishy aftertaste", "Stomach upset", "Loose stools", "Increased bleeding time"],
        "interactions": ["Warfarin", "Aspirin", "Blood pressure medications"],
        "manufacturer": "Seven Seas Healthcare",
        "pack_size": "30 capsules",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.6,
        "reviews": 25640,
        "tags": ["supplement", "omega3", "heart", "fish oil", "fatty acid"]
    },
    {
        "id": 27,
        "name": "Calcium + Vitamin D3",
        "brand": "Shelcal",
        "category": "Vitamins",
        "price": 138,
        "mrp": 178,
        "discount": 22,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Calcium_carbonate_supplement_tablets.jpg/320px-Calcium_carbonate_supplement_tablets.jpg",
        "description": "Combination of Calcium Carbonate and Vitamin D3 to support bone strength, prevent osteoporosis, and treat calcium deficiency.",
        "uses": ["Osteoporosis", "Calcium deficiency", "Bone health", "Dental health", "Muscle cramps"],
        "dosage": "One tablet twice daily after meals.",
        "precautions": ["Take with meals for better absorption", "Avoid excessive intake", "Kidney stone risk in high doses"],
        "side_effects": ["Constipation", "Bloating", "Hypercalcemia (excess)", "Kidney stones (rare)"],
        "interactions": ["Iron supplements", "Thyroid medications", "Tetracyclines", "Fluoroquinolones"],
        "manufacturer": "Elder Pharmaceuticals",
        "pack_size": "15 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.6,
        "reviews": 32450,
        "tags": ["calcium", "bone", "vitamin d", "osteoporosis", "supplement"]
    },

    # ═══════════════ RESPIRATORY ═══════════════
    {
        "id": 28,
        "name": "Salbutamol Inhaler 100mcg",
        "brand": "Asthalin",
        "category": "Respiratory",
        "price": 110,
        "mrp": 145,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Salbutamol_inhaler.jpg/320px-Salbutamol_inhaler.jpg",
        "description": "Salbutamol (Albuterol) inhaler is a fast-acting bronchodilator that provides quick relief from asthma symptoms and bronchospasm.",
        "uses": ["Asthma", "Bronchospasm", "COPD", "Exercise-induced asthma"],
        "dosage": "1–2 puffs every 4–6 hours as needed.",
        "precautions": ["Shake well before use", "Rinse mouth after use", "Not a preventive inhaler"],
        "side_effects": ["Tremors", "Increased heart rate", "Headache", "Nervousness"],
        "interactions": ["Beta-blockers", "Digoxin", "Diuretics"],
        "manufacturer": "Cipla Limited",
        "pack_size": "200 doses",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.6,
        "reviews": 43210,
        "tags": ["asthma", "inhaler", "respiratory", "breathing", "salbutamol"]
    },
    {
        "id": 29,
        "name": "Montelukast 10mg",
        "brand": "Montair",
        "category": "Respiratory",
        "price": 95,
        "mrp": 125,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Montelukast_tablets_10mg.jpg/320px-Montelukast_tablets_10mg.jpg",
        "description": "Montelukast is a leukotriene receptor antagonist used to prevent asthma attacks and treat seasonal allergies.",
        "uses": ["Asthma prevention", "Allergic rhinitis", "Exercise-induced bronchoconstriction"],
        "dosage": "10mg once daily in the evening.",
        "precautions": ["Monitor for mood changes", "Not for acute asthma attacks", "Consult doctor if pregnant"],
        "side_effects": ["Headache", "Stomach pain", "Fever", "Mood changes", "Sleep problems"],
        "interactions": ["Phenobarbital", "Rifampicin", "Gemfibrozil"],
        "manufacturer": "Cipla Limited",
        "pack_size": "10 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.4,
        "reviews": 12340,
        "tags": ["asthma", "allergy", "respiratory", "montelukast", "leukotriene"]
    },
    {
        "id": 30,
        "name": "Budesonide Inhaler 200mcg",
        "brand": "Budecort",
        "category": "Respiratory",
        "price": 285,
        "mrp": 375,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Budesonide_inhaler.jpg/320px-Budesonide_inhaler.jpg",
        "description": "Budesonide is an inhaled corticosteroid used as a controller medication to prevent asthma attacks and reduce airway inflammation.",
        "uses": ["Asthma prevention", "COPD management", "Airway inflammation"],
        "dosage": "1–2 puffs twice daily. Rinse mouth after each use.",
        "precautions": ["Not for acute attacks", "Rinse mouth after use", "Do not stop suddenly"],
        "side_effects": ["Oral thrush", "Hoarseness", "Cough", "Throat irritation"],
        "interactions": ["Ketoconazole", "Ritonavir", "CYP3A4 inhibitors"],
        "manufacturer": "Cipla Limited",
        "pack_size": "200 doses",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 8760,
        "tags": ["asthma", "inhaler", "steroid", "respiratory", "budesonide"]
    },

    # ═══════════════ SKIN CARE ═══════════════
    {
        "id": 31,
        "name": "Clotrimazole Cream 1%",
        "brand": "Candid",
        "category": "Skin Care",
        "price": 48,
        "mrp": 62,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Clotrimazole_cream_tube.jpg/320px-Clotrimazole_cream_tube.jpg",
        "description": "Clotrimazole is an antifungal cream used to treat fungal skin infections including ringworm, athlete's foot, and jock itch.",
        "uses": ["Ringworm", "Athlete's foot", "Jock itch", "Vaginal yeast infection", "Oral thrush"],
        "dosage": "Apply a thin layer to affected area 2–3 times daily for 2–4 weeks.",
        "precautions": ["For external use only", "Avoid contact with eyes", "Discontinue if irritation occurs"],
        "side_effects": ["Mild burning", "Itching", "Skin irritation", "Redness"],
        "interactions": ["Tacrolimus", "Pimecrolimus"],
        "manufacturer": "Glenmark Pharmaceuticals",
        "pack_size": "30g tube",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 23450,
        "tags": ["antifungal", "skin", "ringworm", "cream", "clotrimazole"]
    },
    {
        "id": 32,
        "name": "Hydrocortisone Cream 1%",
        "brand": "Cortizone",
        "category": "Skin Care",
        "price": 55,
        "mrp": 72,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Hydrocortisone_cream_1_percent.jpg/320px-Hydrocortisone_cream_1_percent.jpg",
        "description": "Hydrocortisone cream is a mild topical corticosteroid used to relieve itching, redness, and inflammation from skin conditions.",
        "uses": ["Eczema", "Psoriasis", "Dermatitis", "Insect bites", "Minor skin rashes"],
        "dosage": "Apply a thin layer to affected area 1–4 times daily.",
        "precautions": ["Do not use on face for prolonged periods", "Avoid broken skin", "Not for children under 2"],
        "side_effects": ["Skin thinning (long-term)", "Stretch marks", "Skin discoloration"],
        "interactions": ["Other corticosteroids"],
        "manufacturer": "Johnson & Johnson",
        "pack_size": "15g tube",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.3,
        "reviews": 15430,
        "tags": ["skin", "eczema", "itching", "steroid cream", "hydrocortisone"]
    },
    {
        "id": 33,
        "name": "Tretinoin Cream 0.025%",
        "brand": "Retin-A",
        "category": "Skin Care",
        "price": 185,
        "mrp": 240,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Tretinoin_cream_0.025_percent.jpg/320px-Tretinoin_cream_0.025_percent.jpg",
        "description": "Tretinoin is a retinoid used topically to treat acne and reduce fine lines and wrinkles by accelerating skin cell turnover.",
        "uses": ["Acne", "Anti-aging", "Fine lines and wrinkles", "Hyperpigmentation"],
        "dosage": "Apply a pea-sized amount at night to clean, dry skin.",
        "precautions": ["Use sunscreen daily", "Avoid during pregnancy", "Start with low frequency", "Causes initial purging"],
        "side_effects": ["Skin dryness", "Redness", "Peeling", "Increased sun sensitivity"],
        "interactions": ["Other retinoids", "Benzoyl peroxide", "Salicylic acid"],
        "manufacturer": "Johnson & Johnson",
        "pack_size": "20g tube",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.6,
        "reviews": 18760,
        "tags": ["acne", "skin", "retinoid", "anti-aging", "tretinoin"]
    },

    # ═══════════════ MENTAL HEALTH ═══════════════
    {
        "id": 34,
        "name": "Sertraline 50mg",
        "brand": "Zoloft",
        "category": "Mental Health",
        "price": 145,
        "mrp": 188,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Sertraline_50mg_tablets.jpg/320px-Sertraline_50mg_tablets.jpg",
        "description": "Sertraline is an SSRI antidepressant used to treat depression, anxiety disorders, OCD, PTSD, and panic disorder.",
        "uses": ["Depression", "Anxiety", "OCD", "PTSD", "Panic disorder", "Social anxiety"],
        "dosage": "50mg once daily, may be increased to 200mg as prescribed.",
        "precautions": ["Do not stop suddenly", "Takes 2–4 weeks to show effect", "Monitor for suicidal thoughts initially"],
        "side_effects": ["Nausea", "Diarrhea", "Insomnia", "Sexual dysfunction", "Headache"],
        "interactions": ["MAO inhibitors", "Tramadol", "Warfarin", "Pimozide"],
        "manufacturer": "Pfizer India",
        "pack_size": "10 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.3,
        "reviews": 12340,
        "tags": ["depression", "anxiety", "ssri", "mental health", "sertraline"]
    },
    {
        "id": 35,
        "name": "Alprazolam 0.25mg",
        "brand": "Xanax",
        "category": "Mental Health",
        "price": 38,
        "mrp": 50,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Alprazolam_0.25_mg.jpg/320px-Alprazolam_0.25_mg.jpg",
        "description": "Alprazolam is a benzodiazepine used for short-term treatment of anxiety disorders and panic disorder.",
        "uses": ["Anxiety disorders", "Panic disorder", "Short-term anxiety relief"],
        "dosage": "0.25–0.5mg three times daily as prescribed.",
        "precautions": ["High dependency risk", "Do not stop suddenly", "Avoid alcohol", "Avoid driving"],
        "side_effects": ["Drowsiness", "Dizziness", "Memory problems", "Coordination issues", "Dependency"],
        "interactions": ["Alcohol", "Opioids", "Other CNS depressants", "Ketoconazole"],
        "manufacturer": "Pfizer India",
        "pack_size": "10 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.0,
        "reviews": 8760,
        "tags": ["anxiety", "benzodiazepine", "panic", "mental health", "alprazolam"]
    },

    # ═══════════════ THYROID ═══════════════
    {
        "id": 36,
        "name": "Levothyroxine 50mcg",
        "brand": "Thyronorm",
        "category": "Thyroid",
        "price": 52,
        "mrp": 68,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Levothyroxine_50mcg_tablets.jpg/320px-Levothyroxine_50mcg_tablets.jpg",
        "description": "Levothyroxine is a synthetic thyroid hormone used to treat hypothyroidism (underactive thyroid) and thyroid cancer.",
        "uses": ["Hypothyroidism", "Thyroid hormone replacement", "Thyroid cancer adjunct therapy", "Goiter"],
        "dosage": "Take on empty stomach 30–60 minutes before breakfast.",
        "precautions": ["Take at same time daily", "Empty stomach only", "Regular thyroid function tests"],
        "side_effects": ["Palpitations (if overdosed)", "Weight loss", "Anxiety", "Tremors"],
        "interactions": ["Calcium supplements", "Iron supplements", "Antacids", "Cholestyramine"],
        "manufacturer": "Abbott India",
        "pack_size": "120 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.7,
        "reviews": 45670,
        "tags": ["thyroid", "hypothyroidism", "hormone", "levothyroxine"]
    },

    # ═══════════════ WOMEN'S HEALTH ═══════════════
    {
        "id": 37,
        "name": "Folic Acid 5mg",
        "brand": "Folicid",
        "category": "Women's Health",
        "price": 28,
        "mrp": 38,
        "discount": 26,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Folic_acid_tablets.jpg/320px-Folic_acid_tablets.jpg",
        "description": "Folic acid is a B-vitamin essential for cell growth and development, crucial during pregnancy to prevent neural tube defects.",
        "uses": ["Pregnancy supplement", "Neural tube defect prevention", "Folic acid deficiency", "Anemia"],
        "dosage": "5mg once daily or as prescribed by doctor.",
        "precautions": ["Essential for pre-conception and early pregnancy", "Do not exceed dose without medical advice"],
        "side_effects": ["Nausea (rare)", "Bloating", "Allergic reactions (rare)"],
        "interactions": ["Methotrexate", "Phenytoin", "Sulfasalazine"],
        "manufacturer": "Sun Pharmaceutical",
        "pack_size": "30 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.8,
        "reviews": 32450,
        "tags": ["pregnancy", "folic acid", "women", "anemia", "vitamin b"]
    },
    {
        "id": 38,
        "name": "Iron + Folic Acid",
        "brand": "Feronia-XT",
        "category": "Women's Health",
        "price": 65,
        "mrp": 85,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Iron_supplement_tablets.jpg/320px-Iron_supplement_tablets.jpg",
        "description": "Iron with Folic Acid combination tablet used to treat and prevent iron-deficiency anemia, especially during pregnancy.",
        "uses": ["Iron deficiency anemia", "Pregnancy supplement", "Fatigue and weakness", "Folic acid deficiency"],
        "dosage": "One tablet daily after food.",
        "precautions": ["Take after food to reduce stomach upset", "May cause dark stools (normal)", "Avoid tea/coffee with tablet"],
        "side_effects": ["Constipation", "Dark stools", "Stomach upset", "Nausea"],
        "interactions": ["Antacids", "Tetracyclines", "Calcium supplements", "Fluoroquinolones"],
        "manufacturer": "Meyer Organics",
        "pack_size": "30 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 21340,
        "tags": ["iron", "anemia", "pregnancy", "women", "folic acid"]
    },

    # ═══════════════ EYE CARE ═══════════════
    {
        "id": 39,
        "name": "Ciprofloxacin Eye Drops 0.3%",
        "brand": "Ciplox Eye Drops",
        "category": "Eye Care",
        "price": 42,
        "mrp": 55,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Ciprofloxacin_eye_drops.jpg/320px-Ciprofloxacin_eye_drops.jpg",
        "description": "Antibiotic eye drops used to treat bacterial eye infections including conjunctivitis, corneal ulcers, and blepharitis.",
        "uses": ["Bacterial conjunctivitis", "Corneal ulcers", "Blepharitis", "Eye infections"],
        "dosage": "1–2 drops in affected eye every 2–4 hours as prescribed.",
        "precautions": ["Do not touch dropper tip to eye", "Wash hands before use", "Remove contact lenses before use"],
        "side_effects": ["Mild burning", "Eye irritation", "Bitter taste", "Blurred vision temporarily"],
        "interactions": ["Other eye medications"],
        "manufacturer": "Cipla Limited",
        "pack_size": "5ml bottle",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.4,
        "reviews": 9870,
        "tags": ["eye", "conjunctivitis", "antibiotic", "eye drops", "infection"]
    },
    {
        "id": 40,
        "name": "Lubricating Eye Drops",
        "brand": "Refresh Tears",
        "category": "Eye Care",
        "price": 95,
        "mrp": 125,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Eye_drops_bottle.jpg/320px-Eye_drops_bottle.jpg",
        "description": "Carboxymethylcellulose eye drops provide instant relief from dry, irritated eyes due to computer use, dust, or environmental factors.",
        "uses": ["Dry eyes", "Eye fatigue from screen use", "Environmental eye irritation", "Contact lens discomfort"],
        "dosage": "1–2 drops in each eye as needed.",
        "precautions": ["Remove contact lenses before use", "Wait 15 min before re-inserting lenses", "Discard 4 weeks after opening"],
        "side_effects": ["Mild temporary blurring", "Slight stinging on application"],
        "interactions": ["Other eye drops (wait 5 minutes between applications)"],
        "manufacturer": "Allergan India",
        "pack_size": "10ml bottle",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.7,
        "reviews": 34560,
        "tags": ["eye", "dry eyes", "lubricant", "eye drops", "screen fatigue"]
    },
]

CATEGORIES = [
    {"id": 1,  "name": "Pain Relief",    "icon": "💊", "color": "#e8f5e9", "border": "#4caf50"},
    {"id": 2,  "name": "Antibiotics",    "icon": "🦠", "color": "#e3f2fd", "border": "#2196f3"},
    {"id": 3,  "name": "Allergy",        "icon": "🌿", "color": "#fff3e0", "border": "#ff9800"},
    {"id": 4,  "name": "Diabetes",       "icon": "🩸", "color": "#fce4ec", "border": "#e91e63"},
    {"id": 5,  "name": "Gastric",        "icon": "🫁", "color": "#f3e5f5", "border": "#9c27b0"},
    {"id": 6,  "name": "Cardiac",        "icon": "❤️", "color": "#e8eaf6", "border": "#3f51b5"},
    {"id": 7,  "name": "Vitamins",       "icon": "⚡", "color": "#fffde7", "border": "#ffc107"},
    {"id": 8,  "name": "Respiratory",    "icon": "💨", "color": "#e0f7fa", "border": "#00bcd4"},
    {"id": 9,  "name": "Skin Care",      "icon": "🧴", "color": "#fdf2f8", "border": "#c026d3"},
    {"id": 10, "name": "Mental Health",  "icon": "🧠", "color": "#f0fdf4", "border": "#16a34a"},
    {"id": 11, "name": "Thyroid",        "icon": "🦋", "color": "#fff7ed", "border": "#ea580c"},
    {"id": 12, "name": "Women's Health", "icon": "🌸", "color": "#fdf4ff", "border": "#a855f7"},
    {"id": 13, "name": "Eye Care",       "icon": "👁️", "color": "#ecfeff", "border": "#06b6d4"},
]

# ═══════════════ ADDED MEDICINES (IDs 41–75) ═══════════════

MEDICINES += [

    # ── Pain Relief ──────────────────────────────────────────
    {
        "id": 41,
        "name": "Aceclofenac 100mg",
        "brand": "Zerodol",
        "category": "Pain Relief",
        "price": 44,
        "mrp": 58,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Aceclofenac_tablet.jpg/320px-Aceclofenac_tablet.jpg",
        "description": "Aceclofenac is an NSAID used to relieve pain and inflammation in arthritis, dental pain, and post-operative pain.",
        "uses": ["Rheumatoid arthritis", "Osteoarthritis", "Dental pain", "Back pain", "Post-surgical pain"],
        "dosage": "100mg twice daily after food.",
        "precautions": ["Take with food", "Avoid in peptic ulcer", "Not for kidney or liver disease"],
        "side_effects": ["Stomach upset", "Nausea", "Dizziness", "Elevated liver enzymes"],
        "interactions": ["Warfarin", "Methotrexate", "Lithium", "Diuretics"],
        "manufacturer": "Ipca Laboratories",
        "pack_size": "10 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.3,
        "reviews": 5430,
        "tags": ["pain", "arthritis", "nsaid", "aceclofenac", "inflammation"]
    },
    {
        "id": 42,
        "name": "Naproxen 250mg",
        "brand": "Naprosyn",
        "category": "Pain Relief",
        "price": 38,
        "mrp": 50,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Naproxen_250mg_tablets.jpg/320px-Naproxen_250mg_tablets.jpg",
        "description": "Naproxen is a long-acting NSAID used for arthritis, menstrual cramps, and musculoskeletal pain.",
        "uses": ["Arthritis", "Menstrual cramps", "Gout", "Muscle pain", "Tendinitis"],
        "dosage": "250–500mg twice daily with food.",
        "precautions": ["Take with food or milk", "Avoid in late pregnancy", "Monitor blood pressure"],
        "side_effects": ["Stomach pain", "Heartburn", "Dizziness", "Headache"],
        "interactions": ["Aspirin", "Warfarin", "SSRIs", "ACE inhibitors"],
        "manufacturer": "Roche India",
        "pack_size": "10 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.2,
        "reviews": 4210,
        "tags": ["pain", "arthritis", "naproxen", "menstrual", "nsaid"]
    },

    # ── Antibiotics ───────────────────────────────────────────
    {
        "id": 43,
        "name": "Metronidazole 400mg",
        "brand": "Flagyl",
        "category": "Antibiotics",
        "price": 28,
        "mrp": 38,
        "discount": 26,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Metronidazole_400mg_tablets.jpg/320px-Metronidazole_400mg_tablets.jpg",
        "description": "Metronidazole is an antibiotic and antiprotozoal used to treat bacterial and parasitic infections of the gut, skin, and reproductive system.",
        "uses": ["Bacterial vaginosis", "Giardiasis", "Amoebic dysentery", "Dental infections", "H. pylori eradication"],
        "dosage": "400mg three times daily for 5–7 days as prescribed.",
        "precautions": ["Avoid alcohol completely during use", "Not for first trimester pregnancy", "Complete full course"],
        "side_effects": ["Nausea", "Metallic taste", "Headache", "Dark urine (harmless)"],
        "interactions": ["Alcohol", "Warfarin", "Lithium", "Phenytoin"],
        "manufacturer": "Abbott India",
        "pack_size": "15 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.3,
        "reviews": 6540,
        "tags": ["antibiotic", "infection", "metronidazole", "amoeba", "gut"]
    },
    {
        "id": 44,
        "name": "Cefixime 200mg",
        "brand": "Taxim-O",
        "category": "Antibiotics",
        "price": 92,
        "mrp": 122,
        "discount": 25,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Cefixime_200mg_tablet.jpg/320px-Cefixime_200mg_tablet.jpg",
        "description": "Cefixime is a third-generation cephalosporin antibiotic used to treat urinary tract, ear, throat, and respiratory infections.",
        "uses": ["UTI", "Ear infections", "Throat infections", "Typhoid fever", "Gonorrhoea"],
        "dosage": "200mg twice daily or 400mg once daily for 7–14 days.",
        "precautions": ["Check for cephalosporin allergy", "Complete full course", "Monitor kidney function"],
        "side_effects": ["Diarrhea", "Nausea", "Rash", "Headache"],
        "interactions": ["Warfarin", "Carbamazepine", "Probenecid"],
        "manufacturer": "Alkem Laboratories",
        "pack_size": "10 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.4,
        "reviews": 7650,
        "tags": ["antibiotic", "uti", "throat", "cephalosporin", "cefixime"]
    },
    {
        "id": 45,
        "name": "Levofloxacin 500mg",
        "brand": "Levoday",
        "category": "Antibiotics",
        "price": 110,
        "mrp": 145,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Levofloxacin_500mg_tablets.jpg/320px-Levofloxacin_500mg_tablets.jpg",
        "description": "Levofloxacin is a broad-spectrum fluoroquinolone antibiotic used to treat pneumonia, sinusitis, and urinary tract infections.",
        "uses": ["Pneumonia", "Sinusitis", "UTI", "Skin infections", "Prostatitis"],
        "dosage": "500mg once daily for 7–14 days as prescribed.",
        "precautions": ["Avoid in tendon disorders", "No antacids within 2 hrs", "Stay hydrated"],
        "side_effects": ["Nausea", "Diarrhea", "Headache", "Tendon rupture (rare)", "Insomnia"],
        "interactions": ["NSAIDs", "Warfarin", "Antacids", "Theophylline"],
        "manufacturer": "Wockhardt India",
        "pack_size": "5 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.3,
        "reviews": 5430,
        "tags": ["antibiotic", "pneumonia", "uti", "fluoroquinolone", "levofloxacin"]
    },

    # ── Diabetes ──────────────────────────────────────────────
    {
        "id": 46,
        "name": "Empagliflozin 10mg",
        "brand": "Jardiance",
        "category": "Diabetes",
        "price": 385,
        "mrp": 500,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Empagliflozin_10mg_tablet.jpg/320px-Empagliflozin_10mg_tablet.jpg",
        "description": "Empagliflozin is an SGLT2 inhibitor that lowers blood sugar and also reduces cardiovascular and kidney disease risk in diabetics.",
        "uses": ["Type 2 Diabetes", "Heart failure with reduced ejection fraction", "Kidney protection"],
        "dosage": "10mg once daily in the morning with or without food.",
        "precautions": ["Monitor kidney function", "Watch for UTI symptoms", "Not for Type 1 diabetes"],
        "side_effects": ["Genital yeast infections", "UTI", "Increased urination", "Hypotension"],
        "interactions": ["Insulin", "Sulfonylureas", "Diuretics"],
        "manufacturer": "Boehringer Ingelheim",
        "pack_size": "10 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.6,
        "reviews": 4320,
        "tags": ["diabetes", "sglt2", "heart", "empagliflozin", "blood sugar"]
    },
    {
        "id": 47,
        "name": "Insulin Glargine 100IU/ml",
        "brand": "Lantus",
        "category": "Diabetes",
        "price": 890,
        "mrp": 1150,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Insulin_Glargine_injection.jpg/320px-Insulin_Glargine_injection.jpg",
        "description": "Insulin Glargine is a long-acting basal insulin used to control blood sugar levels in Type 1 and Type 2 diabetes.",
        "uses": ["Type 1 Diabetes", "Type 2 Diabetes", "Basal insulin therapy"],
        "dosage": "As prescribed by doctor. Usually once daily subcutaneous injection.",
        "precautions": ["Monitor blood sugar daily", "Rotate injection sites", "Store in refrigerator"],
        "side_effects": ["Hypoglycemia", "Injection site reactions", "Weight gain", "Lipodystrophy"],
        "interactions": ["Alcohol", "Beta-blockers", "Salicylates", "ACE inhibitors"],
        "manufacturer": "Sanofi India",
        "pack_size": "1 vial (10ml)",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.7,
        "reviews": 3210,
        "tags": ["insulin", "diabetes", "type1", "type2", "long-acting"]
    },

    # ── Cardiac ───────────────────────────────────────────────
    {
        "id": 48,
        "name": "Metoprolol 25mg",
        "brand": "Metolar",
        "category": "Cardiac",
        "price": 45,
        "mrp": 60,
        "discount": 25,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Metoprolol_25mg_tablets.jpg/320px-Metoprolol_25mg_tablets.jpg",
        "description": "Metoprolol is a beta-blocker used to treat high blood pressure, angina, heart failure, and abnormal heart rhythms.",
        "uses": ["Hypertension", "Angina", "Heart failure", "Atrial fibrillation", "Post-heart attack"],
        "dosage": "25–100mg once or twice daily as prescribed.",
        "precautions": ["Do not stop suddenly", "Monitor heart rate", "Not for asthma patients"],
        "side_effects": ["Fatigue", "Dizziness", "Cold hands/feet", "Bradycardia", "Depression"],
        "interactions": ["Calcium channel blockers", "Digoxin", "Clonidine", "MAO inhibitors"],
        "manufacturer": "Cipla Limited",
        "pack_size": "15 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 12340,
        "tags": ["heart", "beta-blocker", "hypertension", "angina", "metoprolol"]
    },
    {
        "id": 49,
        "name": "Clopidogrel 75mg",
        "brand": "Plavix",
        "category": "Cardiac",
        "price": 88,
        "mrp": 115,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Clopidogrel_75mg_tablets.jpg/320px-Clopidogrel_75mg_tablets.jpg",
        "description": "Clopidogrel is an antiplatelet agent used to prevent blood clots in patients with heart disease or after stenting/bypass surgery.",
        "uses": ["Post-angioplasty", "Coronary artery disease", "Stroke prevention", "Peripheral artery disease"],
        "dosage": "75mg once daily after food.",
        "precautions": ["Inform surgeon before any procedure", "Watch for unusual bleeding", "Not during active bleeding"],
        "side_effects": ["Bleeding", "Bruising", "Stomach pain", "Rash"],
        "interactions": ["Aspirin", "NSAIDs", "Proton pump inhibitors", "Warfarin"],
        "manufacturer": "Sanofi India",
        "pack_size": "10 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.6,
        "reviews": 8760,
        "tags": ["heart", "antiplatelet", "clot", "clopidogrel", "cardiac"]
    },
    {
        "id": 50,
        "name": "Furosemide 40mg",
        "brand": "Lasix",
        "category": "Cardiac",
        "price": 18,
        "mrp": 25,
        "discount": 28,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Furosemide_40mg_tablets.jpg/320px-Furosemide_40mg_tablets.jpg",
        "description": "Furosemide is a loop diuretic used to treat fluid retention (oedema) in heart failure, liver disease, and kidney disease.",
        "uses": ["Oedema", "Heart failure", "Hypertension", "Liver cirrhosis", "Kidney disease"],
        "dosage": "20–80mg once or twice daily as prescribed.",
        "precautions": ["Monitor electrolytes", "Increase potassium intake", "Avoid dehydration"],
        "side_effects": ["Frequent urination", "Low potassium", "Dizziness", "Dehydration"],
        "interactions": ["Digoxin", "Lithium", "NSAIDs", "Aminoglycosides"],
        "manufacturer": "Aventis Pharma",
        "pack_size": "10 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.3,
        "reviews": 6540,
        "tags": ["diuretic", "heart failure", "oedema", "furosemide", "blood pressure"]
    },

    # ── Gastric ───────────────────────────────────────────────
    {
        "id": 51,
        "name": "Ranitidine 150mg",
        "brand": "Rantac",
        "category": "Gastric",
        "price": 25,
        "mrp": 34,
        "discount": 26,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Ranitidine_150mg_tablets.jpg/320px-Ranitidine_150mg_tablets.jpg",
        "description": "Ranitidine is an H2 blocker that reduces stomach acid production, used to treat heartburn, GERD, and stomach ulcers.",
        "uses": ["Heartburn", "GERD", "Peptic ulcers", "Zollinger-Ellison syndrome", "Acid indigestion"],
        "dosage": "150mg twice daily or 300mg at bedtime.",
        "precautions": ["Consult doctor for long-term use", "Reduce dose in kidney disease"],
        "side_effects": ["Headache", "Constipation", "Diarrhea", "Dizziness"],
        "interactions": ["Antacids", "Warfarin", "Ketoconazole"],
        "manufacturer": "JB Chemicals",
        "pack_size": "10 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.4,
        "reviews": 18760,
        "tags": ["gastric", "acid", "heartburn", "ranitidine", "h2 blocker"]
    },
    {
        "id": 52,
        "name": "Sucralfate 1g",
        "brand": "Sucral",
        "category": "Gastric",
        "price": 55,
        "mrp": 72,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Sucralfate_tablet_1g.jpg/320px-Sucralfate_tablet_1g.jpg",
        "description": "Sucralfate forms a protective coat over ulcers to promote healing, used for stomach and duodenal ulcers.",
        "uses": ["Duodenal ulcers", "Gastric ulcers", "GERD", "Stress ulcer prevention"],
        "dosage": "1g four times daily on empty stomach.",
        "precautions": ["Take on empty stomach", "Separate from other medicines by 2 hours"],
        "side_effects": ["Constipation", "Dry mouth", "Nausea", "Indigestion"],
        "interactions": ["Antacids", "Fluoroquinolones", "Digoxin", "Warfarin"],
        "manufacturer": "Torrent Pharmaceuticals",
        "pack_size": "10 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.2,
        "reviews": 3210,
        "tags": ["gastric", "ulcer", "sucralfate", "stomach", "protective"]
    },

    # ── Vitamins & Supplements ────────────────────────────────
    {
        "id": 53,
        "name": "Vitamin B12 1500mcg",
        "brand": "Cobadex",
        "category": "Vitamins",
        "price": 95,
        "mrp": 125,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vitamin_B12_tablets.jpg/320px-Vitamin_B12_tablets.jpg",
        "description": "Vitamin B12 supplement used to treat B12 deficiency which causes anaemia, nerve damage, and fatigue.",
        "uses": ["B12 deficiency", "Pernicious anaemia", "Nerve health", "Energy boost", "Vegetarian supplement"],
        "dosage": "1 tablet daily or as prescribed.",
        "precautions": ["Regular B12 levels monitoring for long-term use", "Vegan/vegetarian diet requires supplementation"],
        "side_effects": ["Mild diarrhea (rare)", "Allergic reaction (rare)"],
        "interactions": ["Metformin reduces B12 absorption", "Proton pump inhibitors"],
        "manufacturer": "Elder Pharmaceuticals",
        "pack_size": "30 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.7,
        "reviews": 32450,
        "tags": ["vitamin", "b12", "anaemia", "nerve", "energy", "vegan"]
    },
    {
        "id": 54,
        "name": "Zinc 50mg",
        "brand": "Zincovit",
        "category": "Vitamins",
        "price": 65,
        "mrp": 85,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Zinc_supplement_tablets.jpg/320px-Zinc_supplement_tablets.jpg",
        "description": "Zinc supplement used to boost immunity, support wound healing, and treat zinc deficiency.",
        "uses": ["Zinc deficiency", "Immune support", "Wound healing", "Acne treatment", "Cold & flu support"],
        "dosage": "1 tablet daily after food.",
        "precautions": ["Do not exceed recommended dose", "Take with food to reduce nausea"],
        "side_effects": ["Nausea", "Stomach upset", "Metallic taste", "Reduced copper absorption (high doses)"],
        "interactions": ["Copper supplements", "Iron supplements", "Quinolone antibiotics"],
        "manufacturer": "Apex Laboratories",
        "pack_size": "30 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 21340,
        "tags": ["zinc", "immune", "supplement", "wound healing", "vitamin"]
    },
    {
        "id": 55,
        "name": "Magnesium 250mg",
        "brand": "MagOx",
        "category": "Vitamins",
        "price": 110,
        "mrp": 145,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Magnesium_oxide_supplement.jpg/320px-Magnesium_oxide_supplement.jpg",
        "description": "Magnesium supplement used to treat deficiency, muscle cramps, sleep disorders, and to support heart health.",
        "uses": ["Magnesium deficiency", "Muscle cramps", "Sleep support", "Migraine prevention", "Anxiety"],
        "dosage": "250–500mg daily at bedtime.",
        "precautions": ["Reduce dose in kidney disease", "High doses cause laxative effect"],
        "side_effects": ["Diarrhea", "Nausea", "Stomach cramps"],
        "interactions": ["Tetracyclines", "Bisphosphonates", "Digoxin"],
        "manufacturer": "Himalaya Drug Company",
        "pack_size": "30 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.6,
        "reviews": 15430,
        "tags": ["magnesium", "muscle cramps", "sleep", "supplement", "migraine"]
    },
    {
        "id": 56,
        "name": "Biotin 10mg",
        "brand": "Hairfol",
        "category": "Vitamins",
        "price": 145,
        "mrp": 190,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Biotin_supplement_tablet.jpg/320px-Biotin_supplement_tablet.jpg",
        "description": "Biotin (Vitamin B7) supplement used to support hair growth, strengthen nails, and improve skin health.",
        "uses": ["Hair loss", "Brittle nails", "Skin health", "Biotin deficiency", "Metabolism support"],
        "dosage": "1 tablet daily after breakfast.",
        "precautions": ["Can interfere with thyroid and troponin lab tests", "Inform doctor before tests"],
        "side_effects": ["Acne (high doses)", "Digestive upset (rare)"],
        "interactions": ["Anti-seizure medications", "Lipoic acid"],
        "manufacturer": "Mankind Pharma",
        "pack_size": "30 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.6,
        "reviews": 28760,
        "tags": ["biotin", "hair loss", "nails", "skin", "vitamin b7", "supplement"]
    },

    # ── Respiratory ───────────────────────────────────────────
    {
        "id": 57,
        "name": "Tiotropium Inhaler 18mcg",
        "brand": "Tiova",
        "category": "Respiratory",
        "price": 420,
        "mrp": 550,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Tiotropium_inhaler.jpg/320px-Tiotropium_inhaler.jpg",
        "description": "Tiotropium is a long-acting bronchodilator used once daily for maintenance treatment of COPD.",
        "uses": ["COPD", "Chronic bronchitis", "Emphysema", "Bronchospasm prevention"],
        "dosage": "1 capsule inhaled once daily using the HandiHaler device.",
        "precautions": ["Not for acute bronchospasm", "Avoid contact with eyes", "Capsule is for inhalation only — do not swallow"],
        "side_effects": ["Dry mouth", "Constipation", "Urinary retention", "Blurred vision"],
        "interactions": ["Other anticholinergic drugs"],
        "manufacturer": "Cipla Limited",
        "pack_size": "10 capsules",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.6,
        "reviews": 5430,
        "tags": ["copd", "inhaler", "respiratory", "bronchodilator", "tiotropium"]
    },
    {
        "id": 58,
        "name": "Levosalbutamol 1mg Syrup",
        "brand": "Levolin",
        "category": "Respiratory",
        "price": 52,
        "mrp": 68,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Levosalbutamol_syrup.jpg/320px-Levosalbutamol_syrup.jpg",
        "description": "Levosalbutamol syrup is a bronchodilator used to treat wheezing, breathlessness, and bronchospasm in children and adults.",
        "uses": ["Asthma", "Bronchospasm", "Wheezing", "Chronic bronchitis"],
        "dosage": "5ml (1 teaspoon) twice or three times daily as prescribed.",
        "precautions": ["Not for acute severe asthma without supervision", "Monitor heart rate"],
        "side_effects": ["Tremors", "Palpitations", "Headache", "Hypokalemia (high doses)"],
        "interactions": ["Beta-blockers", "Diuretics", "Digoxin"],
        "manufacturer": "Cipla Limited",
        "pack_size": "100ml bottle",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.4,
        "reviews": 7650,
        "tags": ["asthma", "respiratory", "syrup", "bronchospasm", "children"]
    },

    # ── Skin Care ─────────────────────────────────────────────
    {
        "id": 59,
        "name": "Betamethasone Cream 0.1%",
        "brand": "Betnovate",
        "category": "Skin Care",
        "price": 68,
        "mrp": 88,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Betamethasone_valerate_cream.jpg/320px-Betamethasone_valerate_cream.jpg",
        "description": "Betamethasone is a potent topical corticosteroid used to treat inflammatory skin conditions like eczema and psoriasis.",
        "uses": ["Eczema", "Psoriasis", "Contact dermatitis", "Seborrheic dermatitis", "Lichen planus"],
        "dosage": "Apply thin layer to affected area once or twice daily.",
        "precautions": ["Short-term use only", "Do not use on face", "Not for infected skin", "Not for children under 1 year"],
        "side_effects": ["Skin thinning", "Stretch marks", "Skin discoloration", "Local burning"],
        "interactions": ["Other corticosteroids"],
        "manufacturer": "GSK Pharmaceuticals",
        "pack_size": "20g tube",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.4,
        "reviews": 12340,
        "tags": ["skin", "eczema", "psoriasis", "steroid cream", "betamethasone"]
    },
    {
        "id": 60,
        "name": "Mupirocin Ointment 2%",
        "brand": "Bactroban",
        "category": "Skin Care",
        "price": 115,
        "mrp": 150,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Mupirocin_ointment_tube.jpg/320px-Mupirocin_ointment_tube.jpg",
        "description": "Mupirocin is an antibiotic ointment used to treat bacterial skin infections including impetigo and infected wounds.",
        "uses": ["Impetigo", "Infected wounds", "Folliculitis", "Minor skin infections", "MRSA nasal decolonisation"],
        "dosage": "Apply to affected area 2–3 times daily for 5–10 days.",
        "precautions": ["For external use only", "Avoid contact with eyes", "Not for deep wounds"],
        "side_effects": ["Mild burning", "Stinging", "Itching at application site"],
        "interactions": ["Other topical antibiotics"],
        "manufacturer": "GSK Pharmaceuticals",
        "pack_size": "5g tube",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 9870,
        "tags": ["skin", "antibiotic", "ointment", "wound", "impetigo", "mupirocin"]
    },
    {
        "id": 61,
        "name": "Benzoyl Peroxide 2.5% Gel",
        "brand": "Benzac",
        "category": "Skin Care",
        "price": 145,
        "mrp": 190,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Benzoyl_peroxide_gel_tube.jpg/320px-Benzoyl_peroxide_gel_tube.jpg",
        "description": "Benzoyl peroxide gel is an effective topical treatment for mild to moderate acne that kills acne-causing bacteria.",
        "uses": ["Acne vulgaris", "Whiteheads", "Blackheads", "Inflammatory acne"],
        "dosage": "Apply thin layer once daily at night to clean, dry skin.",
        "precautions": ["Can bleach fabric", "Causes initial dryness", "Use sunscreen during the day", "Avoid eye area"],
        "side_effects": ["Dryness", "Redness", "Peeling", "Sun sensitivity"],
        "interactions": ["Tretinoin (apply at different times)", "Other acne products"],
        "manufacturer": "Galderma India",
        "pack_size": "30g tube",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.4,
        "reviews": 16540,
        "tags": ["acne", "skin", "benzoyl peroxide", "bacteria", "pimple"]
    },

    # ── Mental Health ─────────────────────────────────────────
    {
        "id": 62,
        "name": "Escitalopram 10mg",
        "brand": "Nexito",
        "category": "Mental Health",
        "price": 98,
        "mrp": 128,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Escitalopram_10mg_tablet.jpg/320px-Escitalopram_10mg_tablet.jpg",
        "description": "Escitalopram is an SSRI antidepressant used to treat depression, generalised anxiety disorder, and panic disorder.",
        "uses": ["Depression", "Generalised anxiety disorder", "Panic disorder", "Social anxiety", "OCD"],
        "dosage": "10mg once daily in the morning. May increase to 20mg.",
        "precautions": ["Do not stop suddenly", "Takes 2–4 weeks to work", "Avoid alcohol"],
        "side_effects": ["Nausea", "Insomnia", "Dry mouth", "Sexual dysfunction", "Sweating"],
        "interactions": ["MAO inhibitors", "Tramadol", "Warfarin", "Triptans"],
        "manufacturer": "Sun Pharmaceutical",
        "pack_size": "10 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.4,
        "reviews": 9870,
        "tags": ["depression", "anxiety", "ssri", "escitalopram", "mental health"]
    },
    {
        "id": 63,
        "name": "Melatonin 5mg",
        "brand": "Meloset",
        "category": "Mental Health",
        "price": 85,
        "mrp": 110,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Melatonin_5mg_tablets.jpg/320px-Melatonin_5mg_tablets.jpg",
        "description": "Melatonin is a natural sleep hormone supplement used to treat insomnia, jet lag, and shift work sleep disorder.",
        "uses": ["Insomnia", "Jet lag", "Shift work sleep disorder", "Sleep onset difficulty"],
        "dosage": "2–5mg 30–60 minutes before bedtime.",
        "precautions": ["Short-term use recommended", "May cause drowsiness", "Avoid driving after taking"],
        "side_effects": ["Drowsiness", "Headache", "Dizziness", "Nausea"],
        "interactions": ["Sedatives", "Blood thinners", "Immunosuppressants"],
        "manufacturer": "Aristo Pharmaceuticals",
        "pack_size": "10 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 18760,
        "tags": ["sleep", "insomnia", "melatonin", "jet lag", "mental health"]
    },

    # ── Thyroid ───────────────────────────────────────────────
    {
        "id": 64,
        "name": "Carbimazole 5mg",
        "brand": "Neomercazole",
        "category": "Thyroid",
        "price": 42,
        "mrp": 56,
        "discount": 25,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Carbimazole_5mg_tablets.jpg/320px-Carbimazole_5mg_tablets.jpg",
        "description": "Carbimazole is an antithyroid drug used to treat hyperthyroidism (overactive thyroid) by reducing thyroid hormone production.",
        "uses": ["Hyperthyroidism", "Graves' disease", "Thyroid storm preparation"],
        "dosage": "15–60mg daily in divided doses, reducing as thyroid levels normalise.",
        "precautions": ["Regular thyroid and blood count monitoring", "Report sore throat immediately (agranulocytosis risk)"],
        "side_effects": ["Rash", "Nausea", "Agranulocytosis (rare)", "Headache"],
        "interactions": ["Warfarin", "Digoxin", "Theophylline"],
        "manufacturer": "Roche India",
        "pack_size": "100 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.3,
        "reviews": 3210,
        "tags": ["thyroid", "hyperthyroidism", "graves", "antithyroid", "carbimazole"]
    },

    # ── Women's Health ────────────────────────────────────────
    {
        "id": 65,
        "name": "Mefenamic Acid 500mg",
        "brand": "Meftal-Forte",
        "category": "Women's Health",
        "price": 32,
        "mrp": 42,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Mefenamic_acid_500mg_tablet.jpg/320px-Mefenamic_acid_500mg_tablet.jpg",
        "description": "Mefenamic acid is an NSAID used to relieve menstrual pain (dysmenorrhoea) and heavy periods.",
        "uses": ["Menstrual cramps", "Dysmenorrhoea", "Heavy periods", "Mild to moderate pain"],
        "dosage": "500mg three times daily after food for 3–5 days during menstruation.",
        "precautions": ["Take with food", "Not for peptic ulcer", "Avoid in kidney disease"],
        "side_effects": ["Stomach upset", "Diarrhea", "Headache", "Dizziness"],
        "interactions": ["Warfarin", "Lithium", "ACE inhibitors", "Diuretics"],
        "manufacturer": "Blue Cross Laboratories",
        "pack_size": "10 tablets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.6,
        "reviews": 23450,
        "tags": ["women", "menstrual", "period", "cramps", "dysmenorrhoea", "nsaid"]
    },
    {
        "id": 66,
        "name": "Progesterone 200mg",
        "brand": "Susten",
        "category": "Women's Health",
        "price": 185,
        "mrp": 240,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Progesterone_200mg_capsule.jpg/320px-Progesterone_200mg_capsule.jpg",
        "description": "Micronised progesterone used in assisted reproduction, luteal phase support, and to prevent preterm birth.",
        "uses": ["Luteal phase support in IVF", "Threatened miscarriage", "Preterm birth prevention", "Hormone replacement"],
        "dosage": "200mg once daily at bedtime vaginally or orally as prescribed.",
        "precautions": ["Prescribed use only", "Monitor for clotting disorders", "Not with liver disease"],
        "side_effects": ["Drowsiness", "Dizziness", "Breast tenderness", "Vaginal discharge"],
        "interactions": ["Rifampicin", "Phenytoin", "Carbamazepine"],
        "manufacturer": "Sun Pharmaceutical",
        "pack_size": "10 capsules",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.7,
        "reviews": 8760,
        "tags": ["women", "pregnancy", "ivf", "progesterone", "hormone"]
    },

    # ── Eye Care ──────────────────────────────────────────────
    {
        "id": 67,
        "name": "Timolol Eye Drops 0.5%",
        "brand": "Glucomol",
        "category": "Eye Care",
        "price": 65,
        "mrp": 85,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Timolol_eye_drops.jpg/320px-Timolol_eye_drops.jpg",
        "description": "Timolol eye drops are a beta-blocker used to lower elevated intraocular pressure in glaucoma and ocular hypertension.",
        "uses": ["Glaucoma", "Ocular hypertension"],
        "dosage": "1 drop in affected eye once or twice daily.",
        "precautions": ["Can affect heart rate (systemic absorption)", "Not for asthma patients", "Remove contact lenses before use"],
        "side_effects": ["Stinging", "Eye redness", "Decreased heart rate", "Fatigue"],
        "interactions": ["Oral beta-blockers", "Calcium channel blockers", "Digoxin"],
        "manufacturer": "Cipla Limited",
        "pack_size": "5ml bottle",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.4,
        "reviews": 5430,
        "tags": ["eye", "glaucoma", "eye drops", "timolol", "intraocular pressure"]
    },
    {
        "id": 68,
        "name": "Moxifloxacin Eye Drops 0.5%",
        "brand": "Moxicip",
        "category": "Eye Care",
        "price": 78,
        "mrp": 102,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Moxifloxacin_eye_drops_bottle.jpg/320px-Moxifloxacin_eye_drops_bottle.jpg",
        "description": "Moxifloxacin eye drops are a fourth-generation fluoroquinolone antibiotic for treating bacterial eye infections.",
        "uses": ["Bacterial conjunctivitis", "Corneal ulcer", "Pre/post-operative eye infection prevention"],
        "dosage": "1 drop in affected eye 3 times daily for 7 days.",
        "precautions": ["Remove contact lenses", "Do not touch dropper to eye", "Complete the full course"],
        "side_effects": ["Eye redness", "Mild burning", "Blurred vision temporarily"],
        "interactions": ["Other eye drops (wait 5 minutes between applications)"],
        "manufacturer": "Cipla Limited",
        "pack_size": "5ml bottle",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 7650,
        "tags": ["eye", "conjunctivitis", "antibiotic", "moxifloxacin", "eye drops"]
    },

    # ── Neurological ──────────────────────────────────────────
    {
        "id": 69,
        "name": "Gabapentin 300mg",
        "brand": "Gabantin",
        "category": "Neurological",
        "price": 65,
        "mrp": 85,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Gabapentin_300mg_capsules.jpg/320px-Gabapentin_300mg_capsules.jpg",
        "description": "Gabapentin is used to treat nerve pain (neuropathy), epilepsy, and restless legs syndrome.",
        "uses": ["Neuropathic pain", "Epilepsy", "Post-herpetic neuralgia", "Restless legs syndrome", "Fibromyalgia"],
        "dosage": "300mg three times daily, increasing as needed up to 3600mg/day.",
        "precautions": ["Do not stop suddenly", "Causes drowsiness — avoid driving", "Reduce dose in kidney disease"],
        "side_effects": ["Dizziness", "Drowsiness", "Weight gain", "Oedema", "Blurred vision"],
        "interactions": ["Alcohol", "Opioids", "Antacids", "CNS depressants"],
        "manufacturer": "Sun Pharmaceutical",
        "pack_size": "10 capsules",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.3,
        "reviews": 8760,
        "tags": ["nerve pain", "neuropathy", "epilepsy", "gabapentin", "neurological"]
    },
    {
        "id": 70,
        "name": "Pregabalin 75mg",
        "brand": "Lyrica",
        "category": "Neurological",
        "price": 145,
        "mrp": 188,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Pregabalin_75mg_capsule.jpg/320px-Pregabalin_75mg_capsule.jpg",
        "description": "Pregabalin is used for nerve pain, epilepsy, fibromyalgia, and generalised anxiety disorder.",
        "uses": ["Neuropathic pain", "Fibromyalgia", "Epilepsy", "Generalised anxiety disorder", "Post-herpetic neuralgia"],
        "dosage": "75mg twice daily, may increase to 300mg/day.",
        "precautions": ["Do not stop suddenly", "Avoid alcohol", "Causes dizziness and drowsiness"],
        "side_effects": ["Dizziness", "Drowsiness", "Weight gain", "Blurred vision", "Oedema"],
        "interactions": ["Alcohol", "CNS depressants", "Opioids"],
        "manufacturer": "Pfizer India",
        "pack_size": "10 capsules",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.4,
        "reviews": 6540,
        "tags": ["nerve pain", "fibromyalgia", "anxiety", "pregabalin", "neurological"]
    },
    {
        "id": 71,
        "name": "Sumatriptan 50mg",
        "brand": "Suminat",
        "category": "Neurological",
        "price": 95,
        "mrp": 124,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Sumatriptan_50mg_tablets.jpg/320px-Sumatriptan_50mg_tablets.jpg",
        "description": "Sumatriptan is a triptan used to treat acute migraine attacks with or without aura.",
        "uses": ["Migraine", "Cluster headaches"],
        "dosage": "50–100mg at onset of migraine. May repeat after 2 hours if needed.",
        "precautions": ["Not for prevention — only for acute attacks", "Not for hemiplegic migraine", "Not for cardiovascular disease"],
        "side_effects": ["Chest tightness", "Tingling", "Flushing", "Dizziness", "Nausea"],
        "interactions": ["MAO inhibitors", "SSRIs", "Ergot alkaloids"],
        "manufacturer": "Sun Pharmaceutical",
        "pack_size": "4 tablets",
        "prescription_required": True,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 5430,
        "tags": ["migraine", "headache", "triptan", "sumatriptan", "neurological"]
    },

    # ── Oral Care ─────────────────────────────────────────────
    {
        "id": 72,
        "name": "Chlorhexidine Mouthwash 0.2%",
        "brand": "Hexidine",
        "category": "Oral Care",
        "price": 85,
        "mrp": 110,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Chlorhexidine_mouthwash.jpg/320px-Chlorhexidine_mouthwash.jpg",
        "description": "Chlorhexidine mouthwash is an antiseptic used to treat gum disease, mouth ulcers, and prevent plaque formation.",
        "uses": ["Gingivitis", "Mouth ulcers", "Post-dental surgery care", "Plaque prevention", "Bad breath"],
        "dosage": "Rinse with 10ml for 30 seconds twice daily after brushing.",
        "precautions": ["Do not swallow", "Temporary tooth discoloration (reversible)", "Do not use immediately after brushing with toothpaste"],
        "side_effects": ["Tooth staining", "Altered taste", "Tongue discoloration", "Mouth irritation"],
        "interactions": ["Fluoride toothpaste (use separately)"],
        "manufacturer": "ICPA Health Products",
        "pack_size": "200ml bottle",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.4,
        "reviews": 12340,
        "tags": ["oral", "mouthwash", "gum", "gingivitis", "antiseptic", "chlorhexidine"]
    },
    {
        "id": 73,
        "name": "Benzydamine Mouthwash 0.15%",
        "brand": "Tantum Verde",
        "category": "Oral Care",
        "price": 95,
        "mrp": 125,
        "discount": 24,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Benzydamine_mouthwash.jpg/320px-Benzydamine_mouthwash.jpg",
        "description": "Benzydamine mouthwash provides pain relief and anti-inflammatory action for mouth ulcers, sore throat, and post-op pain.",
        "uses": ["Mouth ulcers", "Sore throat", "Post-tonsillectomy pain", "Oral mucositis from chemotherapy"],
        "dosage": "Rinse or gargle with 15ml every 1.5–3 hours as needed.",
        "precautions": ["Do not swallow", "Not for children under 12", "Avoid prolonged use"],
        "side_effects": ["Numbness", "Stinging", "Nausea", "Dry mouth"],
        "interactions": ["None significant"],
        "manufacturer": "ABIOGEN Pharma (distributed by Pfizer India)",
        "pack_size": "200ml bottle",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.5,
        "reviews": 8760,
        "tags": ["oral", "mouthwash", "sore throat", "ulcer", "benzydamine"]
    },

    # ── First Aid ─────────────────────────────────────────────
    {
        "id": 74,
        "name": "Povidone Iodine 5% Ointment",
        "brand": "Betadine",
        "category": "First Aid",
        "price": 48,
        "mrp": 62,
        "discount": 23,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Betadine_ointment_tube.jpg/320px-Betadine_ointment_tube.jpg",
        "description": "Povidone Iodine antiseptic ointment used to prevent infection in cuts, burns, wounds, and ulcers.",
        "uses": ["Wound disinfection", "Minor burns", "Cuts and abrasions", "Surgical site preparation", "Skin ulcers"],
        "dosage": "Apply to affected area once or twice daily. Cover with dressing.",
        "precautions": ["Do not use over large body surface areas", "Avoid in thyroid disorders", "Not for deep wounds without medical advice"],
        "side_effects": ["Skin staining (temporary)", "Local irritation", "Allergic reaction (rare)"],
        "interactions": ["Hydrogen peroxide (inactivates iodine)", "Mercury-containing antiseptics"],
        "manufacturer": "Win Medicare",
        "pack_size": "20g tube",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.6,
        "reviews": 21340,
        "tags": ["first aid", "wound", "antiseptic", "betadine", "iodine", "burns"]
    },
    {
        "id": 75,
        "name": "Oral Rehydration Salts",
        "brand": "Electral",
        "category": "First Aid",
        "price": 18,
        "mrp": 25,
        "discount": 28,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/ORS_sachets_electral.jpg/320px-ORS_sachets_electral.jpg",
        "description": "Oral Rehydration Salts (ORS) replenish fluids and electrolytes lost during diarrhea, vomiting, and dehydration.",
        "uses": ["Diarrhea", "Dehydration", "Vomiting", "Cholera", "Heat exhaustion", "Sports recovery"],
        "dosage": "Dissolve 1 sachet in 1 litre of clean water. Drink as needed.",
        "precautions": ["Use clean water only", "Discard unused solution after 24 hours", "Seek medical help if no improvement in 24 hrs"],
        "side_effects": ["Nausea (rare)", "Vomiting (if taken too fast)"],
        "interactions": ["None significant"],
        "manufacturer": "Franco Indian Pharmaceuticals",
        "pack_size": "10 sachets",
        "prescription_required": False,
        "in_stock": True,
        "rating": 4.8,
        "reviews": 43210,
        "tags": ["ors", "diarrhea", "dehydration", "electrolyte", "first aid", "rehydration"]
    },
]

# ── Add new categories for new medicines ──────────────────────
CATEGORIES += [
    {"id": 14, "name": "Neurological", "icon": "🧠", "color": "#f0f4ff", "border": "#6366f1"},
    {"id": 15, "name": "Oral Care",    "icon": "🦷", "color": "#f0fdf4", "border": "#22c55e"},
    {"id": 16, "name": "First Aid",    "icon": "🩹", "color": "#fff1f2", "border": "#f43f5e"},
]
